# Generated by Django 5.0.6 on 2024-05-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsandgroups', '0005_alter_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='photou',
        ),
    ]
