# Generated by Django 5.0.6 on 2024-05-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsandgroups', '0012_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=42, unique=True),
            preserve_default=False,
        ),
    ]
