# Generated by Django 5.0.6 on 2024-05-28 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsandgroups', '0013_remove_group_slug_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
