# Generated by Django 5.0.6 on 2024-05-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsandgroups', '0014_alter_student_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
